[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_solc = true
fs_permissions = [{ access = "read", path = "./" }]

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
]
